services:
  - type: web
    name: ChazeFashion-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: |
      python manage.py migrate &&
      gunicorn ChazeFashion.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: ChazeFashion.settings
      - key: SECRET_KEY
        value: your-secret-key
      - key: DATABASE_URL
        value: your-database-url
